import { CocktailIngredientLink } from "./types";

// This file is generated by scripts/import-cocktails.mjs. Do not edit by hand.

export const cocktailIngredientLinks: CocktailIngredientLink[] = [
  {
    "cocktailId": "alexander",
    "ingredientId": "gin",
    "sortOrder": 0,
    "amount": "1/2 oz"
  },
  {
    "cocktailId": "alexander",
    "ingredientId": "creme-de-cacao",
    "sortOrder": 1,
    "amount": "1/2 oz white"
  },
  {
    "cocktailId": "alexander",
    "ingredientId": "light-cream",
    "sortOrder": 2,
    "amount": "2 oz"
  },
  {
    "cocktailId": "alexander",
    "ingredientId": "nutmeg",
    "sortOrder": 3,
    "amount": "по вкусу"
  },
  {
    "cocktailId": "americano",
    "ingredientId": "campari",
    "sortOrder": 0,
    "amount": "1 oz"
  },
  {
    "cocktailId": "americano",
    "ingredientId": "sweet-vermouth",
    "sortOrder": 1,
    "amount": "1 oz red"
  },
  {
    "cocktailId": "americano",
    "ingredientId": "lemon-peel",
    "sortOrder": 2,
    "amount": "Twist of"
  },
  {
    "cocktailId": "americano",
    "ingredientId": "orange-peel",
    "sortOrder": 3,
    "amount": "Twist of"
  },
  {
    "cocktailId": "aviation",
    "ingredientId": "gin",
    "sortOrder": 0,
    "amount": "4.5 cl"
  },
  {
    "cocktailId": "aviation",
    "ingredientId": "lemon-juice",
    "sortOrder": 1,
    "amount": "1.5 cl"
  },
  {
    "cocktailId": "aviation",
    "ingredientId": "maraschino-liqueur",
    "sortOrder": 2,
    "amount": "1.5 cl"
  },
  {
    "cocktailId": "b-52",
    "ingredientId": "baileys-irish-cream",
    "sortOrder": 0,
    "amount": "1/3"
  },
  {
    "cocktailId": "b-52",
    "ingredientId": "grand-marnier",
    "sortOrder": 1,
    "amount": "1/3"
  },
  {
    "cocktailId": "b-52",
    "ingredientId": "kahlua",
    "sortOrder": 2,
    "amount": "1/4"
  },
  {
    "cocktailId": "bellini",
    "ingredientId": "champagne",
    "sortOrder": 0,
    "amount": "6 oz"
  },
  {
    "cocktailId": "bellini",
    "ingredientId": "peach-schnapps",
    "sortOrder": 1,
    "amount": "1 oz"
  },
  {
    "cocktailId": "bramble",
    "ingredientId": "gin",
    "sortOrder": 0,
    "amount": "4 cl"
  },
  {
    "cocktailId": "bramble",
    "ingredientId": "lemon-juice",
    "sortOrder": 1,
    "amount": "1.5 cl"
  },
  {
    "cocktailId": "bramble",
    "ingredientId": "sugar-syrup",
    "sortOrder": 2,
    "amount": "1 cl"
  },
  {
    "cocktailId": "bramble",
    "ingredientId": "creme-de-mure",
    "sortOrder": 3,
    "amount": "1.5 cl"
  },
  {
    "cocktailId": "brooklyn",
    "ingredientId": "rye-whiskey",
    "sortOrder": 0,
    "amount": "2 oz"
  },
  {
    "cocktailId": "brooklyn",
    "ingredientId": "dry-vermouth",
    "sortOrder": 1,
    "amount": "1 oz"
  },
  {
    "cocktailId": "brooklyn",
    "ingredientId": "maraschino-liqueur",
    "sortOrder": 2,
    "amount": "1/4 oz"
  },
  {
    "cocktailId": "brooklyn",
    "ingredientId": "angostura",
    "sortOrder": 3,
    "amount": "3 dashes"
  },
  {
    "cocktailId": "brooklyn",
    "ingredientId": "maraschino-cherry",
    "sortOrder": 4,
    "amount": "1"
  },
  {
    "cocktailId": "caipirinha",
    "ingredientId": "sugar",
    "sortOrder": 0,
    "amount": "2 tsp"
  },
  {
    "cocktailId": "caipirinha",
    "ingredientId": "lime",
    "sortOrder": 1,
    "amount": "1"
  },
  {
    "cocktailId": "caipirinha",
    "ingredientId": "cachaca",
    "sortOrder": 2,
    "amount": "2 1/2 oz"
  },
  {
    "cocktailId": "casino",
    "ingredientId": "gin",
    "sortOrder": 0,
    "amount": "2 oz"
  },
  {
    "cocktailId": "casino",
    "ingredientId": "maraschino-liqueur",
    "sortOrder": 1,
    "amount": "1/4 tsp"
  },
  {
    "cocktailId": "casino",
    "ingredientId": "lemon-juice",
    "sortOrder": 2,
    "amount": "1/4 tsp"
  },
  {
    "cocktailId": "casino",
    "ingredientId": "orange-bitters",
    "sortOrder": 3,
    "amount": "2 dashes"
  },
  {
    "cocktailId": "casino",
    "ingredientId": "cherry",
    "sortOrder": 4,
    "amount": "1"
  },
  {
    "cocktailId": "clover-club",
    "ingredientId": "gin",
    "sortOrder": 0,
    "amount": "1 1/2 oz"
  },
  {
    "cocktailId": "clover-club",
    "ingredientId": "grenadine",
    "sortOrder": 1,
    "amount": "2 tsp"
  },
  {
    "cocktailId": "clover-club",
    "ingredientId": "lemon",
    "sortOrder": 2,
    "amount": "Juice of 1/2"
  },
  {
    "cocktailId": "clover-club",
    "ingredientId": "egg-white",
    "sortOrder": 3,
    "amount": "1"
  },
  {
    "cocktailId": "corpse-reviver",
    "ingredientId": "gin",
    "sortOrder": 0,
    "amount": "3/4 oz"
  },
  {
    "cocktailId": "corpse-reviver",
    "ingredientId": "triple-sec",
    "sortOrder": 1,
    "amount": "3/4 oz"
  },
  {
    "cocktailId": "corpse-reviver",
    "ingredientId": "lillet-blanc",
    "sortOrder": 2,
    "amount": "3/4 oz"
  },
  {
    "cocktailId": "corpse-reviver",
    "ingredientId": "lemon-juice",
    "sortOrder": 3,
    "amount": "3/4 oz"
  },
  {
    "cocktailId": "corpse-reviver",
    "ingredientId": "absinthe",
    "sortOrder": 4,
    "amount": "1 dash"
  },
  {
    "cocktailId": "cosmopolitan",
    "ingredientId": "vodka",
    "sortOrder": 0,
    "amount": "1 1/4 oz"
  },
  {
    "cocktailId": "cosmopolitan",
    "ingredientId": "lime-juice",
    "sortOrder": 1,
    "amount": "1/4 oz"
  },
  {
    "cocktailId": "cosmopolitan",
    "ingredientId": "cointreau",
    "sortOrder": 2,
    "amount": "1/4 oz"
  },
  {
    "cocktailId": "cosmopolitan",
    "ingredientId": "cranberry-juice",
    "sortOrder": 3,
    "amount": "1/4 cup"
  },
  {
    "cocktailId": "cuba-libre",
    "ingredientId": "white-rum",
    "sortOrder": 0,
    "amount": "2 oz"
  },
  {
    "cocktailId": "cuba-libre",
    "ingredientId": "lime",
    "sortOrder": 1,
    "amount": "Juice of 1/2"
  },
  {
    "cocktailId": "cuba-libre",
    "ingredientId": "cola",
    "sortOrder": 2,
    "amount": "по вкусу"
  },
  {
    "cocktailId": "daiquiri",
    "ingredientId": "white-rum",
    "sortOrder": 0,
    "amount": "1 1/2 oz"
  },
  {
    "cocktailId": "daiquiri",
    "ingredientId": "lime",
    "sortOrder": 1,
    "amount": "Juice of 1/2"
  },
  {
    "cocktailId": "daiquiri",
    "ingredientId": "powdered-sugar",
    "sortOrder": 2,
    "amount": "1 tsp"
  },
  {
    "cocktailId": "dark-and-stormy",
    "ingredientId": "dark-rum",
    "sortOrder": 0,
    "amount": "5 cl"
  },
  {
    "cocktailId": "dark-and-stormy",
    "ingredientId": "ginger-beer",
    "sortOrder": 1,
    "amount": "10 cl"
  },
  {
    "cocktailId": "dirty-martini",
    "ingredientId": "vodka",
    "sortOrder": 0,
    "amount": "70ml/2fl oz"
  },
  {
    "cocktailId": "dirty-martini",
    "ingredientId": "dry-vermouth",
    "sortOrder": 1,
    "amount": "1 tbsp"
  },
  {
    "cocktailId": "dirty-martini",
    "ingredientId": "olive-brine",
    "sortOrder": 2,
    "amount": "2 tbsp"
  },
  {
    "cocktailId": "dirty-martini",
    "ingredientId": "lemon",
    "sortOrder": 3,
    "amount": "1 wedge"
  },
  {
    "cocktailId": "dirty-martini",
    "ingredientId": "olive",
    "sortOrder": 4,
    "amount": "1"
  },
  {
    "cocktailId": "dry-martini",
    "ingredientId": "gin",
    "sortOrder": 0,
    "amount": "1 2/3 oz"
  },
  {
    "cocktailId": "dry-martini",
    "ingredientId": "dry-vermouth",
    "sortOrder": 1,
    "amount": "1/3 oz"
  },
  {
    "cocktailId": "dry-martini",
    "ingredientId": "olive",
    "sortOrder": 2,
    "amount": "1"
  },
  {
    "cocktailId": "espresso-martini",
    "ingredientId": "vodka",
    "sortOrder": 0,
    "amount": "5 cl"
  },
  {
    "cocktailId": "espresso-martini",
    "ingredientId": "kahlua",
    "sortOrder": 1,
    "amount": "1 cl"
  },
  {
    "cocktailId": "espresso-martini",
    "ingredientId": "sugar-syrup",
    "sortOrder": 2,
    "amount": "1 dash"
  },
  {
    "cocktailId": "french-75",
    "ingredientId": "gin",
    "sortOrder": 0,
    "amount": "1 1/2 oz"
  },
  {
    "cocktailId": "french-75",
    "ingredientId": "sugar",
    "sortOrder": 1,
    "amount": "2 tsp superfine"
  },
  {
    "cocktailId": "french-75",
    "ingredientId": "lemon-juice",
    "sortOrder": 2,
    "amount": "1 1/2 oz"
  },
  {
    "cocktailId": "french-75",
    "ingredientId": "champagne",
    "sortOrder": 3,
    "amount": "4 oz Chilled"
  },
  {
    "cocktailId": "french-75",
    "ingredientId": "orange",
    "sortOrder": 4,
    "amount": "1"
  },
  {
    "cocktailId": "french-75",
    "ingredientId": "maraschino-cherry",
    "sortOrder": 5,
    "amount": "1"
  },
  {
    "cocktailId": "french-connection",
    "ingredientId": "cognac",
    "sortOrder": 0,
    "amount": "1 1/2 oz"
  },
  {
    "cocktailId": "french-connection",
    "ingredientId": "amaretto",
    "sortOrder": 1,
    "amount": "3/4 oz"
  },
  {
    "cocktailId": "french-martini",
    "ingredientId": "vodka",
    "sortOrder": 0,
    "amount": "4.5 cl"
  },
  {
    "cocktailId": "french-martini",
    "ingredientId": "raspberry-liqueur",
    "sortOrder": 1,
    "amount": "1.5 cl"
  },
  {
    "cocktailId": "french-martini",
    "ingredientId": "pineapple-juice",
    "sortOrder": 2,
    "amount": "1.5 cl"
  },
  {
    "cocktailId": "gimlet",
    "ingredientId": "gin",
    "sortOrder": 0,
    "amount": "2 1/2 oz"
  },
  {
    "cocktailId": "gimlet",
    "ingredientId": "lime-juice",
    "sortOrder": 1,
    "amount": "1/2 oz"
  },
  {
    "cocktailId": "gimlet",
    "ingredientId": "sugar-syrup",
    "sortOrder": 2,
    "amount": "1/2 oz"
  },
  {
    "cocktailId": "gimlet",
    "ingredientId": "lime",
    "sortOrder": 3,
    "amount": "1"
  },
  {
    "cocktailId": "gin-fizz",
    "ingredientId": "gin",
    "sortOrder": 0,
    "amount": "2 oz"
  },
  {
    "cocktailId": "gin-fizz",
    "ingredientId": "lemon",
    "sortOrder": 1,
    "amount": "Juice of 1/2"
  },
  {
    "cocktailId": "gin-fizz",
    "ingredientId": "powdered-sugar",
    "sortOrder": 2,
    "amount": "1 tsp"
  },
  {
    "cocktailId": "gin-fizz",
    "ingredientId": "soda-water",
    "sortOrder": 3,
    "amount": "по вкусу"
  },
  {
    "cocktailId": "gin-rickey",
    "ingredientId": "gin",
    "sortOrder": 0,
    "amount": "2 oz"
  },
  {
    "cocktailId": "gin-rickey",
    "ingredientId": "grenadine",
    "sortOrder": 1,
    "amount": "1 tsp"
  },
  {
    "cocktailId": "gin-rickey",
    "ingredientId": "lemon",
    "sortOrder": 2,
    "amount": "Juice of 1/2"
  },
  {
    "cocktailId": "gin-rickey",
    "ingredientId": "soda-water",
    "sortOrder": 3,
    "amount": "Top up with"
  },
  {
    "cocktailId": "gin-rickey",
    "ingredientId": "lime",
    "sortOrder": 4,
    "amount": "Garnish"
  },
  {
    "cocktailId": "gin-tonic",
    "ingredientId": "gin",
    "sortOrder": 0,
    "amount": "4 cl"
  },
  {
    "cocktailId": "gin-tonic",
    "ingredientId": "tonic",
    "sortOrder": 1,
    "amount": "10 cl"
  },
  {
    "cocktailId": "gin-tonic",
    "ingredientId": "lemon-peel",
    "sortOrder": 2,
    "amount": "1 Slice"
  },
  {
    "cocktailId": "gin-tonic",
    "ingredientId": "ice",
    "sortOrder": 3,
    "amount": "cubes"
  },
  {
    "cocktailId": "godfather",
    "ingredientId": "scotch",
    "sortOrder": 0,
    "amount": "1 1/2 oz"
  },
  {
    "cocktailId": "godfather",
    "ingredientId": "amaretto",
    "sortOrder": 1,
    "amount": "3/4 oz"
  },
  {
    "cocktailId": "greyhound",
    "ingredientId": "vodka",
    "sortOrder": 0,
    "amount": "1 1/2 oz"
  },
  {
    "cocktailId": "greyhound",
    "ingredientId": "grapefruit-juice",
    "sortOrder": 1,
    "amount": "3 oz"
  },
  {
    "cocktailId": "harvey-wallbanger",
    "ingredientId": "vodka",
    "sortOrder": 0,
    "amount": "1 oz"
  },
  {
    "cocktailId": "harvey-wallbanger",
    "ingredientId": "galliano",
    "sortOrder": 1,
    "amount": "1/2 oz"
  },
  {
    "cocktailId": "harvey-wallbanger",
    "ingredientId": "orange-juice",
    "sortOrder": 2,
    "amount": "4 oz"
  },
  {
    "cocktailId": "hemingway-special",
    "ingredientId": "rum",
    "sortOrder": 0,
    "amount": "12 parts"
  },
  {
    "cocktailId": "hemingway-special",
    "ingredientId": "grapefruit-juice",
    "sortOrder": 1,
    "amount": "8 parts"
  },
  {
    "cocktailId": "hemingway-special",
    "ingredientId": "maraschino-liqueur",
    "sortOrder": 2,
    "amount": "3 parts"
  },
  {
    "cocktailId": "hemingway-special",
    "ingredientId": "lime-juice",
    "sortOrder": 3,
    "amount": "3 parts"
  },
  {
    "cocktailId": "irish-coffee",
    "ingredientId": "irish-whiskey",
    "sortOrder": 0,
    "amount": "1 1/2 oz"
  },
  {
    "cocktailId": "irish-coffee",
    "ingredientId": "coffee",
    "sortOrder": 1,
    "amount": "8 oz"
  },
  {
    "cocktailId": "irish-coffee",
    "ingredientId": "sugar",
    "sortOrder": 2,
    "amount": "1 tsp"
  },
  {
    "cocktailId": "irish-coffee",
    "ingredientId": "whipped-cream",
    "sortOrder": 3,
    "amount": "1 tblsp"
  },
  {
    "cocktailId": "jack-rose-cocktail",
    "ingredientId": "apple-brandy",
    "sortOrder": 0,
    "amount": "1 1/2 oz"
  },
  {
    "cocktailId": "jack-rose-cocktail",
    "ingredientId": "grenadine",
    "sortOrder": 1,
    "amount": "1 tsp"
  },
  {
    "cocktailId": "jack-rose-cocktail",
    "ingredientId": "lime",
    "sortOrder": 2,
    "amount": "Juice of 1/2"
  },
  {
    "cocktailId": "john-collins",
    "ingredientId": "bourbon",
    "sortOrder": 0,
    "amount": "2 oz"
  },
  {
    "cocktailId": "john-collins",
    "ingredientId": "lemon-juice",
    "sortOrder": 1,
    "amount": "1 oz"
  },
  {
    "cocktailId": "john-collins",
    "ingredientId": "sugar",
    "sortOrder": 2,
    "amount": "1 tsp superfine"
  },
  {
    "cocktailId": "john-collins",
    "ingredientId": "club-soda",
    "sortOrder": 3,
    "amount": "3 oz"
  },
  {
    "cocktailId": "john-collins",
    "ingredientId": "maraschino-cherry",
    "sortOrder": 4,
    "amount": "1"
  },
  {
    "cocktailId": "john-collins",
    "ingredientId": "orange",
    "sortOrder": 5,
    "amount": "1"
  },
  {
    "cocktailId": "kamikaze",
    "ingredientId": "vodka",
    "sortOrder": 0,
    "amount": "1 oz"
  },
  {
    "cocktailId": "kamikaze",
    "ingredientId": "triple-sec",
    "sortOrder": 1,
    "amount": "1 oz"
  },
  {
    "cocktailId": "kamikaze",
    "ingredientId": "lime-juice",
    "sortOrder": 2,
    "amount": "1 oz"
  },
  {
    "cocktailId": "kir",
    "ingredientId": "creme-de-cassis",
    "sortOrder": 0,
    "amount": "1 part"
  },
  {
    "cocktailId": "kir",
    "ingredientId": "champagne",
    "sortOrder": 1,
    "amount": "5 parts"
  },
  {
    "cocktailId": "kir-royale",
    "ingredientId": "creme-de-cassis",
    "sortOrder": 0,
    "amount": "1 part"
  },
  {
    "cocktailId": "kir-royale",
    "ingredientId": "champagne",
    "sortOrder": 1,
    "amount": "5 parts"
  },
  {
    "cocktailId": "the-last-word",
    "ingredientId": "green-chartreuse",
    "sortOrder": 0,
    "amount": "1 oz"
  },
  {
    "cocktailId": "the-last-word",
    "ingredientId": "maraschino-liqueur",
    "sortOrder": 1,
    "amount": "1 oz"
  },
  {
    "cocktailId": "the-last-word",
    "ingredientId": "lime-juice",
    "sortOrder": 2,
    "amount": "1 oz"
  },
  {
    "cocktailId": "the-last-word",
    "ingredientId": "gin",
    "sortOrder": 3,
    "amount": "1 oz"
  },
  {
    "cocktailId": "lemon-drop",
    "ingredientId": "vodka",
    "sortOrder": 0,
    "amount": "1 1/2 shot"
  },
  {
    "cocktailId": "lemon-drop",
    "ingredientId": "cointreau",
    "sortOrder": 1,
    "amount": "1 1/2 shot"
  },
  {
    "cocktailId": "lemon-drop",
    "ingredientId": "lemon",
    "sortOrder": 2,
    "amount": "Juice of 1 wedge"
  },
  {
    "cocktailId": "long-island-iced-tea",
    "ingredientId": "vodka",
    "sortOrder": 0,
    "amount": "1/2 oz"
  },
  {
    "cocktailId": "long-island-iced-tea",
    "ingredientId": "tequila",
    "sortOrder": 1,
    "amount": "1/2 oz"
  },
  {
    "cocktailId": "long-island-iced-tea",
    "ingredientId": "white-rum",
    "sortOrder": 2,
    "amount": "1/2 oz"
  },
  {
    "cocktailId": "long-island-iced-tea",
    "ingredientId": "gin",
    "sortOrder": 3,
    "amount": "1/2 oz"
  },
  {
    "cocktailId": "long-island-iced-tea",
    "ingredientId": "cola",
    "sortOrder": 4,
    "amount": "1 dash"
  },
  {
    "cocktailId": "long-island-iced-tea",
    "ingredientId": "lemon-peel",
    "sortOrder": 5,
    "amount": "Twist of"
  },
  {
    "cocktailId": "mai-tai",
    "ingredientId": "white-rum",
    "sortOrder": 0,
    "amount": "1 oz"
  },
  {
    "cocktailId": "mai-tai",
    "ingredientId": "orgeat-syrup",
    "sortOrder": 1,
    "amount": "1/2 oz"
  },
  {
    "cocktailId": "mai-tai",
    "ingredientId": "triple-sec",
    "sortOrder": 2,
    "amount": "1/2 oz"
  },
  {
    "cocktailId": "mai-tai",
    "ingredientId": "sweet-and-sour",
    "sortOrder": 3,
    "amount": "1 1/2 oz"
  },
  {
    "cocktailId": "mai-tai",
    "ingredientId": "cherry",
    "sortOrder": 4,
    "amount": "1"
  },
  {
    "cocktailId": "manhattan",
    "ingredientId": "sweet-vermouth",
    "sortOrder": 0,
    "amount": "3/4 oz"
  },
  {
    "cocktailId": "manhattan",
    "ingredientId": "bourbon",
    "sortOrder": 1,
    "amount": "2 1/2 oz Blended"
  },
  {
    "cocktailId": "manhattan",
    "ingredientId": "angostura",
    "sortOrder": 2,
    "amount": "dash"
  },
  {
    "cocktailId": "manhattan",
    "ingredientId": "ice",
    "sortOrder": 3,
    "amount": "2 or 3"
  },
  {
    "cocktailId": "manhattan",
    "ingredientId": "maraschino-cherry",
    "sortOrder": 4,
    "amount": "1"
  },
  {
    "cocktailId": "manhattan",
    "ingredientId": "orange-peel",
    "sortOrder": 5,
    "amount": "1 twist of"
  },
  {
    "cocktailId": "margarita",
    "ingredientId": "tequila",
    "sortOrder": 0,
    "amount": "1 1/2 oz"
  },
  {
    "cocktailId": "margarita",
    "ingredientId": "triple-sec",
    "sortOrder": 1,
    "amount": "1/2 oz"
  },
  {
    "cocktailId": "margarita",
    "ingredientId": "lime-juice",
    "sortOrder": 2,
    "amount": "1 oz"
  },
  {
    "cocktailId": "margarita",
    "ingredientId": "salt",
    "sortOrder": 3,
    "amount": "по вкусу"
  },
  {
    "cocktailId": "martinez-2",
    "ingredientId": "gin",
    "sortOrder": 0,
    "amount": "1 1/2 oz"
  },
  {
    "cocktailId": "martinez-2",
    "ingredientId": "sweet-vermouth",
    "sortOrder": 1,
    "amount": "1 1/2 oz"
  },
  {
    "cocktailId": "martinez-2",
    "ingredientId": "maraschino-liqueur",
    "sortOrder": 2,
    "amount": "1 tsp"
  },
  {
    "cocktailId": "martinez-2",
    "ingredientId": "angostura",
    "sortOrder": 3,
    "amount": "2 dashes"
  },
  {
    "cocktailId": "mary-pickford",
    "ingredientId": "white-rum",
    "sortOrder": 0,
    "amount": "1 1/2 oz"
  },
  {
    "cocktailId": "mary-pickford",
    "ingredientId": "pineapple-juice",
    "sortOrder": 1,
    "amount": "1 oz"
  },
  {
    "cocktailId": "mary-pickford",
    "ingredientId": "maraschino-liqueur",
    "sortOrder": 2,
    "amount": "1/2 tsp"
  },
  {
    "cocktailId": "mary-pickford",
    "ingredientId": "grenadine",
    "sortOrder": 3,
    "amount": "1/2 tsp"
  },
  {
    "cocktailId": "mary-pickford",
    "ingredientId": "maraschino-cherry",
    "sortOrder": 4,
    "amount": "1"
  },
  {
    "cocktailId": "mimosa",
    "ingredientId": "champagne",
    "sortOrder": 0,
    "amount": "Chilled"
  },
  {
    "cocktailId": "mimosa",
    "ingredientId": "orange-juice",
    "sortOrder": 1,
    "amount": "2 oz"
  },
  {
    "cocktailId": "mint-julep",
    "ingredientId": "mint",
    "sortOrder": 0,
    "amount": "4 fresh"
  },
  {
    "cocktailId": "mint-julep",
    "ingredientId": "bourbon",
    "sortOrder": 1,
    "amount": "2 1/2 oz"
  },
  {
    "cocktailId": "mint-julep",
    "ingredientId": "powdered-sugar",
    "sortOrder": 2,
    "amount": "1 tsp"
  },
  {
    "cocktailId": "mint-julep",
    "ingredientId": "water",
    "sortOrder": 3,
    "amount": "2 tsp"
  },
  {
    "cocktailId": "mojito",
    "ingredientId": "white-rum",
    "sortOrder": 0,
    "amount": "2-3 oz"
  },
  {
    "cocktailId": "mojito",
    "ingredientId": "lime",
    "sortOrder": 1,
    "amount": "Juice of 1"
  },
  {
    "cocktailId": "mojito",
    "ingredientId": "sugar",
    "sortOrder": 2,
    "amount": "2 tsp"
  },
  {
    "cocktailId": "mojito",
    "ingredientId": "mint",
    "sortOrder": 3,
    "amount": "2-4"
  },
  {
    "cocktailId": "mojito",
    "ingredientId": "soda-water",
    "sortOrder": 4,
    "amount": "по вкусу"
  },
  {
    "cocktailId": "moscow-mule",
    "ingredientId": "vodka",
    "sortOrder": 0,
    "amount": "2 oz"
  },
  {
    "cocktailId": "moscow-mule",
    "ingredientId": "lime-juice",
    "sortOrder": 1,
    "amount": "2 oz"
  },
  {
    "cocktailId": "moscow-mule",
    "ingredientId": "ginger-ale",
    "sortOrder": 2,
    "amount": "8 oz"
  },
  {
    "cocktailId": "negroni",
    "ingredientId": "gin",
    "sortOrder": 0,
    "amount": "1 oz"
  },
  {
    "cocktailId": "negroni",
    "ingredientId": "campari",
    "sortOrder": 1,
    "amount": "1 oz"
  },
  {
    "cocktailId": "negroni",
    "ingredientId": "sweet-vermouth",
    "sortOrder": 2,
    "amount": "1 oz"
  },
  {
    "cocktailId": "new-york-sour",
    "ingredientId": "blended-whiskey",
    "sortOrder": 0,
    "amount": "2 oz"
  },
  {
    "cocktailId": "new-york-sour",
    "ingredientId": "lemon",
    "sortOrder": 1,
    "amount": "Juice of 1/2"
  },
  {
    "cocktailId": "new-york-sour",
    "ingredientId": "sugar",
    "sortOrder": 2,
    "amount": "1 tsp"
  },
  {
    "cocktailId": "new-york-sour",
    "ingredientId": "red-wine",
    "sortOrder": 3,
    "amount": "(Claret)"
  },
  {
    "cocktailId": "new-york-sour",
    "ingredientId": "lemon",
    "sortOrder": 4,
    "amount": "по вкусу"
  },
  {
    "cocktailId": "new-york-sour",
    "ingredientId": "cherry",
    "sortOrder": 5,
    "amount": "по вкусу"
  },
  {
    "cocktailId": "old-cuban",
    "ingredientId": "white-rum",
    "sortOrder": 0,
    "amount": "2 oz"
  },
  {
    "cocktailId": "old-cuban",
    "ingredientId": "sugar-syrup",
    "sortOrder": 1,
    "amount": "1 oz"
  },
  {
    "cocktailId": "old-cuban",
    "ingredientId": "lime-juice",
    "sortOrder": 2,
    "amount": "1 oz"
  },
  {
    "cocktailId": "old-cuban",
    "ingredientId": "angostura",
    "sortOrder": 3,
    "amount": "2 dashes"
  },
  {
    "cocktailId": "old-cuban",
    "ingredientId": "prosecco",
    "sortOrder": 4,
    "amount": "2 oz"
  },
  {
    "cocktailId": "old-fashioned",
    "ingredientId": "bourbon",
    "sortOrder": 0,
    "amount": "4.5 cL"
  },
  {
    "cocktailId": "old-fashioned",
    "ingredientId": "angostura",
    "sortOrder": 1,
    "amount": "2 dashes"
  },
  {
    "cocktailId": "old-fashioned",
    "ingredientId": "sugar",
    "sortOrder": 2,
    "amount": "1 cube"
  },
  {
    "cocktailId": "old-fashioned",
    "ingredientId": "water",
    "sortOrder": 3,
    "amount": "dash"
  },
  {
    "cocktailId": "old-pal",
    "ingredientId": "rye-whiskey",
    "sortOrder": 0,
    "amount": "2 oz"
  },
  {
    "cocktailId": "old-pal",
    "ingredientId": "campari",
    "sortOrder": 1,
    "amount": "1 oz"
  },
  {
    "cocktailId": "old-pal",
    "ingredientId": "dry-vermouth",
    "sortOrder": 2,
    "amount": "1 oz"
  },
  {
    "cocktailId": "paloma",
    "ingredientId": "grape-soda",
    "sortOrder": 0,
    "amount": "3 oz"
  },
  {
    "cocktailId": "paloma",
    "ingredientId": "tequila",
    "sortOrder": 1,
    "amount": "1 1/2 oz"
  },
  {
    "cocktailId": "pegu-club",
    "ingredientId": "gin",
    "sortOrder": 0,
    "amount": "1 1/2 oz"
  },
  {
    "cocktailId": "pegu-club",
    "ingredientId": "orange-curacao",
    "sortOrder": 1,
    "amount": "3/4 oz"
  },
  {
    "cocktailId": "pegu-club",
    "ingredientId": "lime-juice",
    "sortOrder": 2,
    "amount": "3/4 oz"
  },
  {
    "cocktailId": "pegu-club",
    "ingredientId": "angostura",
    "sortOrder": 3,
    "amount": "1 dash"
  },
  {
    "cocktailId": "pegu-club",
    "ingredientId": "orange-bitters",
    "sortOrder": 4,
    "amount": "1 dash"
  },
  {
    "cocktailId": "penicillin",
    "ingredientId": "blended-scotch",
    "sortOrder": 0,
    "amount": "2 oz"
  },
  {
    "cocktailId": "penicillin",
    "ingredientId": "lemon-juice",
    "sortOrder": 1,
    "amount": "3/4 oz"
  },
  {
    "cocktailId": "penicillin",
    "ingredientId": "honey-syrup",
    "sortOrder": 2,
    "amount": "2 tsp"
  },
  {
    "cocktailId": "penicillin",
    "ingredientId": "ginger-syrup",
    "sortOrder": 3,
    "amount": "2 tsp"
  },
  {
    "cocktailId": "penicillin",
    "ingredientId": "islay-single-malt-scotch",
    "sortOrder": 4,
    "amount": "1/4 oz"
  },
  {
    "cocktailId": "pina-colada",
    "ingredientId": "white-rum",
    "sortOrder": 0,
    "amount": "3 oz"
  },
  {
    "cocktailId": "pina-colada",
    "ingredientId": "coconut-milk",
    "sortOrder": 1,
    "amount": "3 tblsp"
  },
  {
    "cocktailId": "pina-colada",
    "ingredientId": "pineapple",
    "sortOrder": 2,
    "amount": "3 tblsp"
  },
  {
    "cocktailId": "pink-gin",
    "ingredientId": "bitters",
    "sortOrder": 0,
    "amount": "3 dashes"
  },
  {
    "cocktailId": "pink-gin",
    "ingredientId": "gin",
    "sortOrder": 1,
    "amount": "2 oz"
  },
  {
    "cocktailId": "pisco-sour",
    "ingredientId": "pisco",
    "sortOrder": 0,
    "amount": "2 oz"
  },
  {
    "cocktailId": "pisco-sour",
    "ingredientId": "lemon-juice",
    "sortOrder": 1,
    "amount": "1 oz"
  },
  {
    "cocktailId": "pisco-sour",
    "ingredientId": "sugar",
    "sortOrder": 2,
    "amount": "1-2 tblsp"
  },
  {
    "cocktailId": "pisco-sour",
    "ingredientId": "ice",
    "sortOrder": 3,
    "amount": "1"
  },
  {
    "cocktailId": "pisco-sour",
    "ingredientId": "egg-white",
    "sortOrder": 4,
    "amount": "по вкусу"
  },
  {
    "cocktailId": "planter-s-punch",
    "ingredientId": "dark-rum",
    "sortOrder": 0,
    "amount": "4.5 cL"
  },
  {
    "cocktailId": "planter-s-punch",
    "ingredientId": "orange-juice",
    "sortOrder": 1,
    "amount": "3 cl"
  },
  {
    "cocktailId": "planter-s-punch",
    "ingredientId": "pineapple-juice",
    "sortOrder": 2,
    "amount": "3.5 cl"
  },
  {
    "cocktailId": "planter-s-punch",
    "ingredientId": "grenadine",
    "sortOrder": 3,
    "amount": "1 cl"
  },
  {
    "cocktailId": "planter-s-punch",
    "ingredientId": "sugar-syrup",
    "sortOrder": 4,
    "amount": "1 cl"
  },
  {
    "cocktailId": "planter-s-punch",
    "ingredientId": "angostura",
    "sortOrder": 5,
    "amount": "4 drops"
  },
  {
    "cocktailId": "ramos-gin-fizz",
    "ingredientId": "gin",
    "sortOrder": 0,
    "amount": "4.5 cL"
  },
  {
    "cocktailId": "ramos-gin-fizz",
    "ingredientId": "lemon-juice",
    "sortOrder": 1,
    "amount": "3 cl"
  },
  {
    "cocktailId": "ramos-gin-fizz",
    "ingredientId": "sugar-syrup",
    "sortOrder": 2,
    "amount": "3 cl"
  },
  {
    "cocktailId": "ramos-gin-fizz",
    "ingredientId": "cream",
    "sortOrder": 3,
    "amount": "6 cl"
  },
  {
    "cocktailId": "ramos-gin-fizz",
    "ingredientId": "egg-white",
    "sortOrder": 4,
    "amount": "1"
  },
  {
    "cocktailId": "ramos-gin-fizz",
    "ingredientId": "vanilla-extract",
    "sortOrder": 5,
    "amount": "2 drop"
  },
  {
    "cocktailId": "ramos-gin-fizz",
    "ingredientId": "soda-water",
    "sortOrder": 6,
    "amount": "2 cl"
  },
  {
    "cocktailId": "rusty-nail",
    "ingredientId": "scotch",
    "sortOrder": 0,
    "amount": "1 1/2 oz"
  },
  {
    "cocktailId": "rusty-nail",
    "ingredientId": "drambuie",
    "sortOrder": 1,
    "amount": "1/2 oz"
  },
  {
    "cocktailId": "rusty-nail",
    "ingredientId": "lemon-peel",
    "sortOrder": 2,
    "amount": "1 twist of"
  },
  {
    "cocktailId": "sazerac",
    "ingredientId": "ricard",
    "sortOrder": 0,
    "amount": "1 tsp"
  },
  {
    "cocktailId": "sazerac",
    "ingredientId": "sugar",
    "sortOrder": 1,
    "amount": "1/2 tsp superfine"
  },
  {
    "cocktailId": "sazerac",
    "ingredientId": "peychaud-bitters",
    "sortOrder": 2,
    "amount": "2 dashes"
  },
  {
    "cocktailId": "sazerac",
    "ingredientId": "water",
    "sortOrder": 3,
    "amount": "1 tsp"
  },
  {
    "cocktailId": "sazerac",
    "ingredientId": "bourbon",
    "sortOrder": 4,
    "amount": "2 oz"
  },
  {
    "cocktailId": "sazerac",
    "ingredientId": "lemon-peel",
    "sortOrder": 5,
    "amount": "1 twist of"
  },
  {
    "cocktailId": "sea-breeze",
    "ingredientId": "vodka",
    "sortOrder": 0,
    "amount": "1 1/2 oz"
  },
  {
    "cocktailId": "sea-breeze",
    "ingredientId": "cranberry-juice",
    "sortOrder": 1,
    "amount": "4 oz"
  },
  {
    "cocktailId": "sea-breeze",
    "ingredientId": "grapefruit-juice",
    "sortOrder": 2,
    "amount": "1 oz"
  },
  {
    "cocktailId": "sidecar",
    "ingredientId": "cognac",
    "sortOrder": 0,
    "amount": "2 oz"
  },
  {
    "cocktailId": "sidecar",
    "ingredientId": "cointreau",
    "sortOrder": 1,
    "amount": "1/2 oz"
  },
  {
    "cocktailId": "sidecar",
    "ingredientId": "lemon-juice",
    "sortOrder": 2,
    "amount": "1 oz"
  },
  {
    "cocktailId": "spritz",
    "ingredientId": "prosecco",
    "sortOrder": 0,
    "amount": "6 cl"
  },
  {
    "cocktailId": "spritz",
    "ingredientId": "campari",
    "sortOrder": 1,
    "amount": "4 cl"
  },
  {
    "cocktailId": "spritz",
    "ingredientId": "soda-water",
    "sortOrder": 2,
    "amount": "splash"
  },
  {
    "cocktailId": "tequila-sunrise",
    "ingredientId": "tequila",
    "sortOrder": 0,
    "amount": "2 measures"
  },
  {
    "cocktailId": "tequila-sunrise",
    "ingredientId": "orange-juice",
    "sortOrder": 1,
    "amount": "по вкусу"
  },
  {
    "cocktailId": "tequila-sunrise",
    "ingredientId": "grenadine",
    "sortOrder": 2,
    "amount": "по вкусу"
  },
  {
    "cocktailId": "tom-collins",
    "ingredientId": "gin",
    "sortOrder": 0,
    "amount": "2 oz"
  },
  {
    "cocktailId": "tom-collins",
    "ingredientId": "lemon-juice",
    "sortOrder": 1,
    "amount": "1 oz"
  },
  {
    "cocktailId": "tom-collins",
    "ingredientId": "sugar",
    "sortOrder": 2,
    "amount": "1 tsp superfine"
  },
  {
    "cocktailId": "tom-collins",
    "ingredientId": "club-soda",
    "sortOrder": 3,
    "amount": "3 oz"
  },
  {
    "cocktailId": "tom-collins",
    "ingredientId": "maraschino-cherry",
    "sortOrder": 4,
    "amount": "1"
  },
  {
    "cocktailId": "tom-collins",
    "ingredientId": "orange",
    "sortOrder": 5,
    "amount": "1"
  },
  {
    "cocktailId": "vesper",
    "ingredientId": "gin",
    "sortOrder": 0,
    "amount": "6 cl"
  },
  {
    "cocktailId": "vesper",
    "ingredientId": "vodka",
    "sortOrder": 1,
    "amount": "1.5 cl"
  },
  {
    "cocktailId": "vesper",
    "ingredientId": "lillet-blanc",
    "sortOrder": 2,
    "amount": "0.75 cl"
  },
  {
    "cocktailId": "whiskey-sour",
    "ingredientId": "blended-whiskey",
    "sortOrder": 0,
    "amount": "2 oz"
  },
  {
    "cocktailId": "whiskey-sour",
    "ingredientId": "lemon",
    "sortOrder": 1,
    "amount": "Juice of 1/2"
  },
  {
    "cocktailId": "whiskey-sour",
    "ingredientId": "powdered-sugar",
    "sortOrder": 2,
    "amount": "1/2 tsp"
  },
  {
    "cocktailId": "whiskey-sour",
    "ingredientId": "cherry",
    "sortOrder": 3,
    "amount": "1"
  },
  {
    "cocktailId": "whiskey-sour",
    "ingredientId": "lemon",
    "sortOrder": 4,
    "amount": "1/2 slice"
  },
  {
    "cocktailId": "white-lady",
    "ingredientId": "gin",
    "sortOrder": 0,
    "amount": "4cl"
  },
  {
    "cocktailId": "white-lady",
    "ingredientId": "triple-sec",
    "sortOrder": 1,
    "amount": "3cl"
  },
  {
    "cocktailId": "white-lady",
    "ingredientId": "lemon-juice",
    "sortOrder": 2,
    "amount": "2cl"
  },
  {
    "cocktailId": "white-russian",
    "ingredientId": "vodka",
    "sortOrder": 0,
    "amount": "2 oz"
  },
  {
    "cocktailId": "white-russian",
    "ingredientId": "coffee-liqueur",
    "sortOrder": 1,
    "amount": "1 oz"
  },
  {
    "cocktailId": "white-russian",
    "ingredientId": "light-cream",
    "sortOrder": 2,
    "amount": "по вкусу"
  },
  {
    "cocktailId": "zombie",
    "ingredientId": "rum",
    "sortOrder": 0,
    "amount": "1 1/2 oz"
  },
  {
    "cocktailId": "zombie",
    "ingredientId": "gold-rum",
    "sortOrder": 1,
    "amount": "1 1/2 oz"
  },
  {
    "cocktailId": "zombie",
    "ingredientId": "151-proof-rum",
    "sortOrder": 2,
    "amount": "1 oz"
  },
  {
    "cocktailId": "zombie",
    "ingredientId": "pernod",
    "sortOrder": 3,
    "amount": "1 tsp"
  },
  {
    "cocktailId": "zombie",
    "ingredientId": "grenadine",
    "sortOrder": 4,
    "amount": "1 tsp"
  },
  {
    "cocktailId": "zombie",
    "ingredientId": "lime-juice",
    "sortOrder": 5,
    "amount": "1 tsp"
  },
  {
    "cocktailId": "zombie",
    "ingredientId": "angostura",
    "sortOrder": 6,
    "amount": "1 drop"
  }
];
