import { CocktailRecord } from "./types";

// This file is generated by scripts/import-cocktails.mjs. Do not edit by hand.

export const cocktailRecords: CocktailRecord[] = [
  {
    "id": "alexander",
    "name": "Александр",
    "baseSpirit": "Джин",
    "taste": [
      "sweet",
      "strong"
    ],
    "strength": "strong",
    "glassName": "Коктейльный бокал",
    "steps": [
      "Встряхни все ингредиенты со льдом и процеди в коктейльный бокал.",
      "Sprinkle Мускатный орех on верх и Подавай."
    ]
  },
  {
    "id": "americano",
    "name": "Американо",
    "baseSpirit": "Кампари",
    "taste": [
      "sour",
      "bitter",
      "strong"
    ],
    "strength": "strong",
    "glassName": "Коллинз",
    "steps": [
      "Налей Кампари и vermouth over Лед в бокал, add a немного содовой и Укрась половину дольки апельсина."
    ]
  },
  {
    "id": "aviation",
    "name": "Авиация",
    "baseSpirit": "Джин",
    "taste": [
      "refreshing",
      "sweet",
      "sour",
      "strong"
    ],
    "strength": "strong",
    "glassName": "Коктейльный бокал",
    "steps": [
      "Добавь все ингредиенты в шейкер со льдом.",
      "Хорошо встряхни и процеди в коктейльный бокал.",
      "Укрась a Вишня."
    ]
  },
  {
    "id": "b-52",
    "name": "Б-52",
    "baseSpirit": "Baileys",
    "taste": [
      "sweet",
      "strong"
    ],
    "strength": "strong",
    "glassName": "Шот",
    "steps": [
      "Выложи ингредиенты слоями в шот.",
      "Подавай with a Перемешайrer."
    ]
  },
  {
    "id": "bellini",
    "name": "Беллини",
    "baseSpirit": "Персиковый шнапс",
    "taste": [
      "refreshing"
    ],
    "strength": "medium",
    "glassName": "Флюте",
    "steps": [
      "Pour Персик purée в chilled flute, add sparkling wine.",
      "Аккуратно перемешай."
    ]
  },
  {
    "id": "bramble",
    "name": "Брамбл",
    "baseSpirit": "Джин",
    "taste": [
      "refreshing",
      "sweet",
      "sour",
      "strong"
    ],
    "strength": "light",
    "glassName": "Рокс",
    "steps": [
      "Наполни бокал колотым льдом.",
      "Собери джин, лимонный сок и сироп поверх льда.",
      "Перемешай, и затем pour blackberry liqueur over in a circular fashion to create marbling effect.",
      "Укрась two blackberries и дольку лимона."
    ]
  },
  {
    "id": "brooklyn",
    "name": "Бруклин",
    "baseSpirit": "Ржаной виски",
    "taste": [
      "sweet",
      "bitter",
      "strong"
    ],
    "strength": "strong",
    "glassName": "Коктейльный бокал",
    "steps": [
      "Смешай ингредиенты со льдом и Перемешай до охлаждения.",
      "Процеди в охлажденный коктейльный бокал."
    ]
  },
  {
    "id": "caipirinha",
    "name": "Кайпиринья",
    "baseSpirit": "Кашаса",
    "taste": [
      "sweet",
      "sour"
    ],
    "strength": "light",
    "glassName": "Рокс",
    "steps": [
      "Place Лайм и Сахар в old fashioned бокал и Слегка разомни (mash the two ingredients together используя a Слегка разомниr or a wooden spoon).",
      "Наполни бокал льдом и add the Cachaça."
    ]
  },
  {
    "id": "casino",
    "name": "Казино",
    "baseSpirit": "Джин",
    "taste": [
      "refreshing",
      "sweet",
      "sour",
      "bitter",
      "strong"
    ],
    "strength": "strong",
    "glassName": "Коктейльный бокал",
    "steps": [
      "Налей все ингредиенты в Встряхниr with кубики льда.",
      "Хорошо встряхни.",
      "Процеди в охлажденный коктейльный бокал.",
      "Укрась a Лимон twist и a maraschino Вишня.",
      "Подавай without a straw."
    ]
  },
  {
    "id": "clover-club",
    "name": "Кловер Клаб",
    "baseSpirit": "Джин",
    "taste": [
      "sweet",
      "sour"
    ],
    "strength": "light",
    "glassName": "Коктейльный бокал",
    "steps": [
      "Dry Встряхни ингредиенты to emulsify, add Лед, Встряхни и Подавайd straight up."
    ]
  },
  {
    "id": "corpse-reviver",
    "name": "Корпс Ревайвер",
    "baseSpirit": "Джин",
    "taste": [
      "refreshing",
      "sweet",
      "sour",
      "strong"
    ],
    "strength": "strong",
    "glassName": "Коктейльный бокал",
    "steps": [
      "Встряхни, Процеди, straight up, коктейльный бокал rinsed with Абсент"
    ]
  },
  {
    "id": "cosmopolitan",
    "name": "Космополитен",
    "baseSpirit": "Водка",
    "taste": [
      "refreshing",
      "sweet",
      "sour",
      "strong"
    ],
    "strength": "light",
    "glassName": "Коктейльный бокал",
    "steps": [
      "Добавь все ингредиенты в шейкер со льдом.",
      "Хорошо встряхни и double Процеди в large коктейльный бокал.",
      "Укрась Лайм wheel."
    ]
  },
  {
    "id": "cuba-libre",
    "name": "Куба либре",
    "baseSpirit": "Белый ром",
    "taste": [
      "sweet",
      "sour"
    ],
    "strength": "light",
    "glassName": "Хайбол",
    "steps": [
      "Build all ingredients in a бокал коллинз filled со льдом.",
      "Укрась дольку лайма."
    ]
  },
  {
    "id": "daiquiri",
    "name": "Дайкири",
    "baseSpirit": "Белый ром",
    "taste": [
      "sweet",
      "sour"
    ],
    "strength": "light",
    "glassName": "Коктейльный бокал",
    "steps": [
      "Налей все ингредиенты в Встряхниr with кубики льда.",
      "Хорошо встряхни.",
      "Процеди in chilled коктейльный бокал."
    ]
  },
  {
    "id": "dark-and-stormy",
    "name": "Дарк-н-сторми",
    "baseSpirit": "Темный ром",
    "taste": [
      "refreshing"
    ],
    "strength": "medium",
    "glassName": "Хайбол",
    "steps": [
      "In a хайбол filled со льдом add 6cl Темный ром и Долей Джинger beer.",
      "Укрась дольку лайма."
    ]
  },
  {
    "id": "dirty-martini",
    "name": "Грязный мартини",
    "baseSpirit": "Водка",
    "taste": [
      "sour",
      "bitter",
      "strong"
    ],
    "strength": "strong",
    "glassName": "Коктейльный бокал",
    "steps": [
      "Налей Водка, Сухой вермут и Оливковый рассол в a cocktail Встряхниr with a handful Лед и Хорошо встряхни.",
      "Rub the rim a martini бокал with the wedge Лимон.",
      "Процеди the contents the cocktail Встряхниr в the бокал и add the Оливка.",
      "A dirty Martini contains a splash Оливковый рассол or Оливка juЛед и is typically Украсьed with an Оливка."
    ]
  },
  {
    "id": "dry-martini",
    "name": "Сухой мартини",
    "baseSpirit": "Джин",
    "taste": [
      "bitter",
      "strong"
    ],
    "strength": "strong",
    "glassName": "Коктейльный бокал",
    "steps": [
      "Straight: Налей все ингредиенты в mixing бокал with кубики льда.",
      "Перемешай well.",
      "Процеди in chilled martini коктейльный бокал.",
      "Squeeze oil from Лимон peel onto the drink, or Укрась Оливка."
    ]
  },
  {
    "id": "espresso-martini",
    "name": "Эспрессо мартини",
    "baseSpirit": "Водка",
    "taste": [
      "sweet",
      "strong"
    ],
    "strength": "strong",
    "glassName": "Коктейльный бокал",
    "steps": [
      "Налей ингредиенты в Встряхниr filled со льдом, Встряхни vigorously, и Процеди в chilled martini бокал"
    ]
  },
  {
    "id": "french-75",
    "name": "Френч 75",
    "baseSpirit": "Джин",
    "taste": [
      "refreshing",
      "sweet",
      "sour"
    ],
    "strength": "light",
    "glassName": "Коллинз",
    "steps": [
      "Смешай Джин, Сахар, и Лимон juЛед in a cocktail Встряхниr filled со льдом.",
      "Встряхни vigorously и Процеди в a chilled Шампанское бокал.",
      "Долей Шампанское.",
      "Аккуратно перемешай."
    ]
  },
  {
    "id": "french-connection",
    "name": "Французская связь",
    "baseSpirit": "Коньяк",
    "taste": [
      "strong"
    ],
    "strength": "strong",
    "glassName": "Рокс",
    "steps": [
      "Налей все ингредиенты directly в old fashioned бокал наполненный кубики льда.",
      "Аккуратно перемешай."
    ]
  },
  {
    "id": "french-martini",
    "name": "Французский мартини",
    "baseSpirit": "Водка",
    "taste": [
      "refreshing",
      "sweet",
      "strong"
    ],
    "strength": "strong",
    "glassName": "Коктейльный бокал",
    "steps": [
      "Налей все ингредиенты в Встряхниr with кубики льда.",
      "Хорошо встряхни и Процеди в охлажденный коктейльный бокал.",
      "Squeeze oil from Лимон peel onto the drink."
    ]
  },
  {
    "id": "gimlet",
    "name": "Гимлет",
    "baseSpirit": "Джин",
    "taste": [
      "refreshing",
      "sweet",
      "sour"
    ],
    "strength": "light",
    "glassName": "Коктейльный бокал",
    "steps": [
      "Add all the ingredients to a Встряхниr и Наполни льдом.",
      "Встряхни, и Процеди в охлажденный коктейльный бокал or an Old Fashioned бокал наполненный fresh Лед.",
      "Укрась a Лайм wheel."
    ]
  },
  {
    "id": "gin-fizz",
    "name": "Джин физз",
    "baseSpirit": "Джин",
    "taste": [
      "sweet",
      "sour"
    ],
    "strength": "light",
    "glassName": "Хайбол",
    "steps": [
      "Встряхни все ингредиенты со льдом cubes, except Газированная вода.",
      "Налей в бокал.",
      "Долей Газированная вода."
    ]
  },
  {
    "id": "gin-rickey",
    "name": "Джин рики",
    "baseSpirit": "Джин",
    "taste": [
      "refreshing",
      "sweet",
      "sour"
    ],
    "strength": "light",
    "glassName": "Хайбол",
    "steps": [
      "Half-fill a tall бокал со льдом.",
      "Mix the Джин и Гренадин together и pour over the Лед.",
      "Add the Лайм or Лимон juЛед и верх off with Газированная вода.",
      "Decorate the бокал with Лайм и/or дольку лимонаs."
    ]
  },
  {
    "id": "gin-tonic",
    "name": "Джин-тоник",
    "baseSpirit": "Джин",
    "taste": [
      "refreshing",
      "sour"
    ],
    "strength": "medium",
    "glassName": "Хайбол",
    "steps": [
      "Fill a хайбол со льдом, Налей Джин, Долей Тоник и squeeze a Лимон wedge и Укрась a Лимон wedge."
    ]
  },
  {
    "id": "godfather",
    "name": "Крестный отец",
    "baseSpirit": "Скотч",
    "taste": [
      "strong"
    ],
    "strength": "strong",
    "glassName": "Рокс",
    "steps": [
      "Налей все ингредиенты directly в old fashioned бокал наполненный кубики льда.",
      "Аккуратно перемешай."
    ]
  },
  {
    "id": "greyhound",
    "name": "Грейхаунд",
    "baseSpirit": "Водка",
    "taste": [
      "refreshing",
      "sweet",
      "sour"
    ],
    "strength": "medium",
    "glassName": "Коллинз",
    "steps": [
      "Add the Водка to a бокал коллинз filled со льдом.",
      "Долей Грейпфрутовый сок и Перемешай."
    ]
  },
  {
    "id": "harvey-wallbanger",
    "name": "Харви Воллбангер",
    "baseSpirit": "Водка",
    "taste": [
      "refreshing",
      "sweet"
    ],
    "strength": "medium",
    "glassName": "Коллинз",
    "steps": [
      "Перемешай the Водка и orange juЛед со льдом in the бокал, затем Аккуратно добавь сверху the Гальяно on верх.",
      "Укрась и Подавай."
    ]
  },
  {
    "id": "hemingway-special",
    "name": "Хемингуэй спешл",
    "baseSpirit": "Ром",
    "taste": [
      "refreshing",
      "sweet",
      "sour",
      "strong"
    ],
    "strength": "light",
    "glassName": "Коктейльный бокал",
    "steps": [
      "Налей все ингредиенты в a Встряхниr со льдом.",
      "Встряхни."
    ]
  },
  {
    "id": "irish-coffee",
    "name": "Айриш кофе",
    "baseSpirit": "Irish whiskey",
    "taste": [
      "sweet"
    ],
    "strength": "light",
    "glassName": "Бокал для айриш кофе",
    "steps": [
      "Heat the Кофе, Виски и Сахар; do not boil.",
      "Налей в бокал и Долей Сливки; Подавай hot."
    ]
  },
  {
    "id": "jack-rose-cocktail",
    "name": "Джек Роуз",
    "baseSpirit": "Яблочный бренди",
    "taste": [
      "sweet",
      "sour"
    ],
    "strength": "light",
    "glassName": "Коктейльный бокал",
    "steps": [
      "Встряхни все ингредиенты со льдом, Процеди в a коктейльный бокал, и Подавай."
    ]
  },
  {
    "id": "john-collins",
    "name": "Джон Коллинз",
    "baseSpirit": "Бурбон",
    "taste": [
      "refreshing",
      "sweet",
      "sour"
    ],
    "strength": "light",
    "glassName": "Коллинз",
    "steps": [
      "Налей все ингредиенты directly в хайбол filled со льдом.",
      "Аккуратно перемешай.",
      "Укрась.",
      "Add a dash Ангостура."
    ]
  },
  {
    "id": "kamikaze",
    "name": "Камикадзе",
    "baseSpirit": "Водка",
    "taste": [
      "refreshing",
      "sweet",
      "sour",
      "strong"
    ],
    "strength": "strong",
    "glassName": "Коктейльный бокал",
    "steps": [
      "Встряхни all ingredients together со льдом.",
      "Процеди в бокал, Укрась и Подавай."
    ]
  },
  {
    "id": "kir",
    "name": "Кир",
    "baseSpirit": "Крем де кассис",
    "taste": [
      "refreshing"
    ],
    "strength": "medium",
    "glassName": "Винный бокал",
    "steps": [
      "Add the crème de cassis to the bottom the бокал, затем Долей wine."
    ]
  },
  {
    "id": "kir-royale",
    "name": "Кир Рояль",
    "baseSpirit": "Крем де кассис",
    "taste": [
      "refreshing"
    ],
    "strength": "medium",
    "glassName": "Флюте",
    "steps": [
      "Pour Крем де кассис in бокал, gently pour Шампанское on верх"
    ]
  },
  {
    "id": "the-last-word",
    "name": "Последнее слово",
    "baseSpirit": "Джин",
    "taste": [
      "refreshing",
      "sweet",
      "sour",
      "strong"
    ],
    "strength": "strong",
    "glassName": "Коктейльный бокал",
    "steps": [
      "Встряхни со льдом и Процеди в a коктейльный бокал."
    ]
  },
  {
    "id": "lemon-drop",
    "name": "Лимон дроп",
    "baseSpirit": "Водка",
    "taste": [
      "sour",
      "strong"
    ],
    "strength": "strong",
    "glassName": "Коктейльный бокал",
    "steps": [
      "Встряхни и Процеди в охлажденный коктейльный бокал rimmed with Сахар."
    ]
  },
  {
    "id": "long-island-iced-tea",
    "name": "Лонг-Айленд айс ти",
    "baseSpirit": "Водка",
    "taste": [
      "sweet",
      "sour",
      "strong"
    ],
    "strength": "strong",
    "glassName": "Хайбол",
    "steps": [
      "Mix all contents in a хайбол и sitr gently.",
      "Add dash Coca-Кола for the coloring и Укрась Лимон or Лайм twist."
    ]
  },
  {
    "id": "mai-tai",
    "name": "Май Тай",
    "baseSpirit": "Белый ром",
    "taste": [
      "sweet",
      "strong"
    ],
    "strength": "strong",
    "glassName": "Коллинз",
    "steps": [
      "Встряхни все ингредиенты со льдом.",
      "Процеди в бокал.",
      "Укрась и Подавай with straw."
    ]
  },
  {
    "id": "manhattan",
    "name": "Манхэттен",
    "baseSpirit": "Бурбон",
    "taste": [
      "bitter",
      "strong"
    ],
    "strength": "strong",
    "glassName": "Коктейльный бокал",
    "steps": [
      "Перемешайred over Лед, Процедиed в a chilled бокал, Украсьed, и Подавайd up."
    ]
  },
  {
    "id": "margarita",
    "name": "Маргарита",
    "baseSpirit": "Текила",
    "taste": [
      "refreshing",
      "sweet",
      "sour",
      "strong"
    ],
    "strength": "strong",
    "glassName": "Коктейльный бокал",
    "steps": [
      "Rub the rim the бокал with the Лайм slЛед to make the salt stick to it.",
      "Take care to moisten only the outer rim и sprinkle the salt on it.",
      "The salt should present to the lips the imbiber и never mix в the cocktail.",
      "Встряхни the other ingredients со льдом, затем carefully Налей в the бокал."
    ]
  },
  {
    "id": "martinez-2",
    "name": "Мартинез",
    "baseSpirit": "Джин",
    "taste": [
      "sweet",
      "bitter",
      "strong"
    ],
    "strength": "strong",
    "glassName": "Коктейльный бокал",
    "steps": [
      "Add all ingredients to a mixing бокал и Наполни льдом.",
      "Перемешай until chilled, и Процеди в a chilled coupe бокал."
    ]
  },
  {
    "id": "mary-pickford",
    "name": "Мэри Пикфорд",
    "baseSpirit": "Белый ром",
    "taste": [
      "refreshing",
      "sweet",
      "strong"
    ],
    "strength": "strong",
    "glassName": "Коктейльный бокал",
    "steps": [
      "Встряхни и Процеди в a chilled large коктейльный бокал"
    ]
  },
  {
    "id": "mimosa",
    "name": "Мимоза",
    "baseSpirit": "Шампанское",
    "taste": [
      "refreshing",
      "sweet"
    ],
    "strength": "light",
    "glassName": "Флюте",
    "steps": [
      "Ensure both ingredients are well chilled, затем mix в the бокал.",
      "Подавай cold."
    ]
  },
  {
    "id": "mint-julep",
    "name": "Мятный джулеп",
    "baseSpirit": "Бурбон",
    "taste": [
      "refreshing",
      "sweet"
    ],
    "strength": "light",
    "glassName": "Коллинз",
    "steps": [
      "In a хайбол gently Слегка разомни the Мята, Сахар и water.",
      "Fill the бокал with cracked Лед, add Бурбон и Перемешай well until the бокал is well frosted.",
      "Укрась a Мята sprig."
    ]
  },
  {
    "id": "mojito",
    "name": "Мохито",
    "baseSpirit": "Белый ром",
    "taste": [
      "refreshing",
      "sweet",
      "sour"
    ],
    "strength": "light",
    "glassName": "Хайбол",
    "steps": [
      "Слегка разомни Мята leaves with Сахар и Лайм juЛед.",
      "Add a немного содовой и fill the бокал with cracked Лед.",
      "Налей Ром и Долей Газированная вода.",
      "Укрась и Подавай with straw."
    ]
  },
  {
    "id": "moscow-mule",
    "name": "Московский мул",
    "baseSpirit": "Водка",
    "taste": [
      "refreshing",
      "sweet",
      "sour"
    ],
    "strength": "light",
    "glassName": "Медная кружка",
    "steps": [
      "Смешай Водка и Джинger beer in a хайбол filled со льдом.",
      "Add Лайм juЛед.",
      "Аккуратно перемешай.",
      "Укрась."
    ]
  },
  {
    "id": "negroni",
    "name": "Негрони",
    "baseSpirit": "Джин",
    "taste": [
      "bitter",
      "strong"
    ],
    "strength": "strong",
    "glassName": "Рокс",
    "steps": [
      "Перемешай в бокал over Лед, Укрась и Подавай."
    ]
  },
  {
    "id": "new-york-sour",
    "name": "Нью-Йорк сауэр",
    "baseSpirit": "Купажированный виски",
    "taste": [
      "sweet",
      "sour"
    ],
    "strength": "light",
    "glassName": "Сауэр",
    "steps": [
      "Встряхни Купажированный виски, juЛед Лимон, и powdered Сахар со льдом и Процеди в a Виски sour бокал.",
      "Аккуратно добавь сверху claret on верх.",
      "Decorate with the half-slЛед Лимон и the Вишня и Подавай."
    ]
  },
  {
    "id": "old-cuban",
    "name": "Олд Кьюбан",
    "baseSpirit": "Белый ром",
    "taste": [
      "refreshing",
      "sweet",
      "sour",
      "bitter"
    ],
    "strength": "light",
    "glassName": "Коктейльный бокал",
    "steps": [
      "Встряхни a handful Мята, 2oz white Ром, 1oz Сахар syrup, 1oz Лайм juЛед и 2 dashes Ангостура со льдом.",
      "Double Процеди в a бокал и Долей 2oz Просекко."
    ]
  },
  {
    "id": "old-fashioned",
    "name": "Олд фэшнд",
    "baseSpirit": "Бурбон",
    "taste": [
      "sweet",
      "bitter",
      "strong"
    ],
    "strength": "light",
    "glassName": "Рокс",
    "steps": [
      "Place Сахар cube in old fashioned бокал и saturate with Биттер, add a dash plain water.",
      "Слегка разомни until dissolved.",
      "Наполни бокал льдом cubes и add Виски.",
      "Укрась orange twist, и a cocktail Вишня."
    ]
  },
  {
    "id": "old-pal",
    "name": "Олд Пал",
    "baseSpirit": "Ржаной виски",
    "taste": [
      "bitter",
      "strong"
    ],
    "strength": "strong",
    "glassName": "Nick & Nora",
    "steps": [
      "Chill коктейльный бокал.",
      "Add ingredients to a mixing бокал, и fill 2/3 full со льдом.",
      "Перемешай about 20 seconds.",
      "Empty коктейльный бокал и Процеди в the бокал.",
      "Укрась a twist Лимон peel."
    ]
  },
  {
    "id": "paloma",
    "name": "Палома",
    "baseSpirit": "Текила",
    "taste": [
      "refreshing"
    ],
    "strength": "medium",
    "glassName": "Коллинз",
    "steps": [
      "Перемешай together и Подавай over Лед."
    ]
  },
  {
    "id": "pegu-club",
    "name": "Пегу Клаб",
    "baseSpirit": "Джин",
    "taste": [
      "refreshing",
      "sweet",
      "sour",
      "bitter",
      "strong"
    ],
    "strength": "strong",
    "glassName": "Коктейльный бокал",
    "steps": [
      "Встряхни, Процеди, up, коктейльный бокал"
    ]
  },
  {
    "id": "penicillin",
    "name": "Пенициллин",
    "baseSpirit": "Купажированный скотч",
    "taste": [
      "refreshing",
      "sweet",
      "sour"
    ],
    "strength": "light",
    "glassName": "Рокс",
    "steps": [
      "Встряхни Купажированный скотч, Лимон juЛед, Медовый сироп и Джинger syrup со льдом.",
      "Процеди over large Лед in chilled rocks бокал.",
      "Аккуратно добавь сверху smoky Скотч on верх (be sure to use a smoky Скотч such as an Islay single malt).",
      "Укрась candied Джинger."
    ]
  },
  {
    "id": "pina-colada",
    "name": "Пина колада",
    "baseSpirit": "Белый ром",
    "taste": [
      "refreshing"
    ],
    "strength": "medium",
    "glassName": "Коллинз",
    "steps": [
      "Mix with crushed Лед in blender until smooth.",
      "Налей в chilled бокал, Укрась и Подавай."
    ]
  },
  {
    "id": "pink-gin",
    "name": "Пинк джин",
    "baseSpirit": "Джин",
    "taste": [
      "bitter",
      "strong"
    ],
    "strength": "strong",
    "glassName": "Бокал для белого вина",
    "steps": [
      "Налей Биттер в a wine бокал.",
      "Swirl the бокал to coat the inside with the Биттер, Встряхни out the excess.",
      "Налей Джин в the бокал.",
      "Do not add Лед."
    ]
  },
  {
    "id": "pisco-sour",
    "name": "Писко сауэр",
    "baseSpirit": "Писко",
    "taste": [
      "refreshing",
      "sweet",
      "sour"
    ],
    "strength": "light",
    "glassName": "Коктейльный бокал",
    "steps": [
      "Vigorously Встряхни и Процеди contents in a cocktail Встряхниr with кубики льда, затем Налей в бокал и Укрась Биттер."
    ]
  },
  {
    "id": "planter-s-punch",
    "name": "Плантерс панч",
    "baseSpirit": "Темный ром",
    "taste": [
      "refreshing",
      "sweet",
      "bitter"
    ],
    "strength": "light",
    "glassName": "Хайбол",
    "steps": [
      "Squeeze an orange и Процеди the juЛед.",
      "Put all the ingredients in a Встряхниr filled со льдом и Встряхни for at least 12 seconds.",
      "Процеди в a хайбол и decorate with a pineapple wedge or fruit your choЛед."
    ]
  },
  {
    "id": "ramos-gin-fizz",
    "name": "Рамос джин физз",
    "baseSpirit": "Джин",
    "taste": [
      "refreshing",
      "sweet",
      "sour"
    ],
    "strength": "light",
    "glassName": "Хайбол",
    "steps": [
      "Prepare all the ingredients on the counter to be able to work well и quickly, especially the Сливки и Яичный белок.",
      "Pour all the ingredients в a Встряхниr.",
      "Встряхни vigorously for 1 minute: Сливки и Яичный белок must be mixed perfectly, so don't rush.",
      "Now open the Встряхниr и put some Лед и Встряхни for 1-2 minutes.",
      "It depends on how long you can resist!",
      "Налей в a хайбол, add a splash soda и Укрась to taste.",
      "Ramos Джин Fizz was once drunk as an invigorating drink or even as a breakfast, try it as an aperitif и after dinner и you will discover a little gem now lost."
    ]
  },
  {
    "id": "rusty-nail",
    "name": "Ржавый гвоздь",
    "baseSpirit": "Скотч",
    "taste": [
      "sour"
    ],
    "strength": "medium",
    "glassName": "Рокс",
    "steps": [
      "Налей Скотч и Драмбуи в an рокс almost наполненный кубики льда.",
      "Перемешай well.",
      "Укрась the Лимон twist."
    ]
  },
  {
    "id": "sazerac",
    "name": "Сазерак",
    "baseSpirit": "Бурбон",
    "taste": [
      "sweet",
      "sour",
      "bitter",
      "strong"
    ],
    "strength": "light",
    "glassName": "Рокс",
    "steps": [
      "Rinse a chilled рокс with the Абсент, add crushed Лед, и set it aside.",
      "Перемешай the remaining ingredients over Лед и set it aside.",
      "Discard the Лед и any excess Абсент from the prepared бокал, и Процеди the drink в the бокал.",
      "Add the Лимон peel for Укрась."
    ]
  },
  {
    "id": "sea-breeze",
    "name": "Морской бриз",
    "baseSpirit": "Водка",
    "taste": [
      "refreshing",
      "sweet",
      "sour"
    ],
    "strength": "light",
    "glassName": "Хайбол",
    "steps": [
      "Build all ingredients in a хайбол filled со льдом.",
      "Укрась дольку лайма."
    ]
  },
  {
    "id": "sidecar",
    "name": "Сайдкар",
    "baseSpirit": "Коньяк",
    "taste": [
      "refreshing",
      "sweet",
      "sour",
      "strong"
    ],
    "strength": "strong",
    "glassName": "Коктейльный бокал",
    "steps": [
      "Налей все ингредиенты в cocktail Встряхниr filled со льдом.",
      "Хорошо встряхни и процеди в коктейльный бокал."
    ]
  },
  {
    "id": "spritz",
    "name": "Спритц",
    "baseSpirit": "Кампари",
    "taste": [
      "refreshing",
      "bitter"
    ],
    "strength": "light",
    "glassName": "Рокс",
    "steps": [
      "Build в бокал over Лед, Укрась и Подавай."
    ]
  },
  {
    "id": "tequila-sunrise",
    "name": "Текила санрайз",
    "baseSpirit": "Текила",
    "taste": [
      "refreshing",
      "sweet"
    ],
    "strength": "light",
    "glassName": "Хайбол",
    "steps": [
      "Налей Текила и orange juЛед в бокал over Лед.",
      "Add the Гренадин, which will sink to the bottom.",
      "Аккуратно перемешай to create the sunrise effect.",
      "Укрась и Подавай."
    ]
  },
  {
    "id": "tom-collins",
    "name": "Том Коллинз",
    "baseSpirit": "Джин",
    "taste": [
      "refreshing",
      "sweet",
      "sour"
    ],
    "strength": "light",
    "glassName": "Коллинз",
    "steps": [
      "In a Встряхниr half-наполненный кубики льда, Смешай the Джин, Лимон juЛед, и Сахар.",
      "Хорошо встряхни.",
      "Процеди в a бокал коллинз alomst наполненный кубики льда.",
      "Add the Содовая.",
      "Перемешай и Укрась the Вишня и the дольку апельсина."
    ]
  },
  {
    "id": "vesper",
    "name": "Веспер",
    "baseSpirit": "Джин",
    "taste": [
      "strong"
    ],
    "strength": "strong",
    "glassName": "Коктейльный бокал",
    "steps": [
      "Встряхни over Лед until well chilled, затем Процеди в a deep goblet и Укрась a thin slЛед Лимон peel."
    ]
  },
  {
    "id": "whiskey-sour",
    "name": "Виски сауэр",
    "baseSpirit": "Купажированный виски",
    "taste": [
      "sweet",
      "sour"
    ],
    "strength": "light",
    "glassName": "Рокс",
    "steps": [
      "Встряхни со льдом.",
      "Процеди в chilled бокал, Укрась и Подавай.",
      "If Подавайd 'On the rocks', Процеди ingredients в рокс filled со льдом."
    ]
  },
  {
    "id": "white-lady",
    "name": "Белая леди",
    "baseSpirit": "Джин",
    "taste": [
      "refreshing",
      "sweet",
      "sour",
      "strong"
    ],
    "strength": "strong",
    "glassName": "Коктейльный бокал",
    "steps": [
      "Добавь все ингредиенты в шейкер со льдом.",
      "Хорошо встряхни и Процеди в large коктейльный бокал."
    ]
  },
  {
    "id": "white-russian",
    "name": "Белый русский",
    "baseSpirit": "Водка",
    "taste": [
      "sweet",
      "strong"
    ],
    "strength": "strong",
    "glassName": "Рокс",
    "steps": [
      "Pour Водка и Кофе liqueur over кубики льда in an рокс.",
      "Fill with light Сливки и Подавай."
    ]
  },
  {
    "id": "zombie",
    "name": "Зомби",
    "baseSpirit": "Ром",
    "taste": [
      "refreshing",
      "sweet",
      "sour",
      "bitter",
      "strong"
    ],
    "strength": "strong",
    "glassName": "Харрикейн",
    "steps": [
      "Blend at high speed for no more than 5 seconds.",
      "Налей в a бокал, add кубики льда to fill, затем add the Укрась.",
      "*Donn’s mix: Bring 3 crushed cinnamon sticks, 1 cup Сахар и 1 cup water to a boil, Перемешайring until the Сахар is dissolved.",
      "Simmer for 2 minutes, затем remove from the heat и let sit for at least 2 hours before Процедиing в a clean бокал bottle.",
      "Затем add 1 part the syrup и 2 parts fresh Грейпфрутовый сок together."
    ]
  }
];
