import { Ingredient } from "./types";

// This file is generated by scripts/import-cocktails.mjs. Do not edit by hand.

export const ingredients: Ingredient[] = [
  {
    "id": "absinthe",
    "name": "Абсент",
    "category": "spirit"
  },
  {
    "id": "amaretto",
    "name": "Амаретто",
    "category": "liqueur"
  },
  {
    "id": "pineapple-juice",
    "name": "Ананасовый сок",
    "category": "mixer"
  },
  {
    "id": "angostura",
    "name": "Ангостура",
    "category": "liqueur"
  },
  {
    "id": "orange-peel",
    "name": "Апельсиновая цедра",
    "category": "other"
  },
  {
    "id": "orange-bitters",
    "name": "Апельсиновый биттер",
    "category": "liqueur"
  },
  {
    "id": "orange-juice",
    "name": "Апельсиновый сок",
    "category": "citrus"
  },
  {
    "id": "white-rum",
    "name": "Белый ром",
    "category": "spirit"
  },
  {
    "id": "bitters",
    "name": "Биттер",
    "category": "liqueur"
  },
  {
    "id": "bourbon",
    "name": "Бурбон",
    "category": "spirit"
  },
  {
    "id": "cherry",
    "name": "Вишня",
    "category": "other"
  },
  {
    "id": "vodka",
    "name": "Водка",
    "category": "spirit"
  },
  {
    "id": "soda-water",
    "name": "Газированная вода",
    "category": "mixer"
  },
  {
    "id": "galliano",
    "name": "Гальяно",
    "category": "other"
  },
  {
    "id": "grapefruit-juice",
    "name": "Грейпфрутовый сок",
    "category": "citrus"
  },
  {
    "id": "grenadine",
    "name": "Гренадин",
    "category": "sweetener"
  },
  {
    "id": "gin",
    "name": "Джин",
    "category": "spirit"
  },
  {
    "id": "drambuie",
    "name": "Драмбуи",
    "category": "other"
  },
  {
    "id": "ginger-beer",
    "name": "Имбирное пиво",
    "category": "mixer"
  },
  {
    "id": "ginger-ale",
    "name": "Имбирный эль",
    "category": "mixer"
  },
  {
    "id": "kahlua",
    "name": "Калуа",
    "category": "liqueur"
  },
  {
    "id": "campari",
    "name": "Кампари",
    "category": "liqueur"
  },
  {
    "id": "cachaca",
    "name": "Кашаса",
    "category": "spirit"
  },
  {
    "id": "coconut-milk",
    "name": "Кокосовое молоко",
    "category": "mixer"
  },
  {
    "id": "cola",
    "name": "Кола",
    "category": "mixer"
  },
  {
    "id": "cognac",
    "name": "Коньяк",
    "category": "spirit"
  },
  {
    "id": "coffee",
    "name": "Кофе",
    "category": "mixer"
  },
  {
    "id": "coffee-liqueur",
    "name": "Кофейный ликер",
    "category": "liqueur"
  },
  {
    "id": "creme-de-cacao",
    "name": "Крем де какао",
    "category": "liqueur"
  },
  {
    "id": "creme-de-cassis",
    "name": "Крем де кассис",
    "category": "liqueur"
  },
  {
    "id": "creme-de-mure",
    "name": "Крем де мюр",
    "category": "liqueur"
  },
  {
    "id": "cointreau",
    "name": "Куантро",
    "category": "liqueur"
  },
  {
    "id": "blended-whiskey",
    "name": "Купажированный виски",
    "category": "spirit"
  },
  {
    "id": "blended-scotch",
    "name": "Купажированный скотч",
    "category": "spirit"
  },
  {
    "id": "lime",
    "name": "Лайм",
    "category": "citrus"
  },
  {
    "id": "ice",
    "name": "Лед",
    "category": "other"
  },
  {
    "id": "lemon",
    "name": "Лимон",
    "category": "citrus"
  },
  {
    "id": "lemon-juice",
    "name": "Лимонный сок",
    "category": "citrus"
  },
  {
    "id": "maraschino-liqueur",
    "name": "Мараскино",
    "category": "liqueur"
  },
  {
    "id": "honey-syrup",
    "name": "Медовый сироп",
    "category": "sweetener"
  },
  {
    "id": "nutmeg",
    "name": "Мускатный орех",
    "category": "other"
  },
  {
    "id": "mint",
    "name": "Мята",
    "category": "other"
  },
  {
    "id": "olive",
    "name": "Оливка",
    "category": "other"
  },
  {
    "id": "olive-brine",
    "name": "Оливковый рассол",
    "category": "other"
  },
  {
    "id": "peach-schnapps",
    "name": "Персиковый шнапс",
    "category": "liqueur"
  },
  {
    "id": "pisco",
    "name": "Писко",
    "category": "spirit"
  },
  {
    "id": "prosecco",
    "name": "Просекко",
    "category": "mixer"
  },
  {
    "id": "rye-whiskey",
    "name": "Ржаной виски",
    "category": "spirit"
  },
  {
    "id": "rum",
    "name": "Ром",
    "category": "spirit"
  },
  {
    "id": "151-proof-rum",
    "name": "Ром 151",
    "category": "spirit"
  },
  {
    "id": "sugar",
    "name": "Сахар",
    "category": "sweetener"
  },
  {
    "id": "sugar-syrup",
    "name": "Сахарный сироп",
    "category": "sweetener"
  },
  {
    "id": "scotch",
    "name": "Скотч",
    "category": "spirit"
  },
  {
    "id": "sweet-vermouth",
    "name": "Сладкий вермут",
    "category": "liqueur"
  },
  {
    "id": "cream",
    "name": "Сливки",
    "category": "mixer"
  },
  {
    "id": "club-soda",
    "name": "Содовая",
    "category": "mixer"
  },
  {
    "id": "lime-juice",
    "name": "Сок лайма",
    "category": "citrus"
  },
  {
    "id": "dry-vermouth",
    "name": "Сухой вермут",
    "category": "liqueur"
  },
  {
    "id": "tequila",
    "name": "Текила",
    "category": "spirit"
  },
  {
    "id": "dark-rum",
    "name": "Темный ром",
    "category": "spirit"
  },
  {
    "id": "tonic",
    "name": "Тоник",
    "category": "mixer"
  },
  {
    "id": "triple-sec",
    "name": "Трипл-сек",
    "category": "liqueur"
  },
  {
    "id": "champagne",
    "name": "Шампанское",
    "category": "mixer"
  },
  {
    "id": "apple-brandy",
    "name": "Яблочный бренди",
    "category": "spirit"
  },
  {
    "id": "egg-white",
    "name": "Яичный белок",
    "category": "other"
  },
  {
    "id": "baileys-irish-cream",
    "name": "Baileys",
    "category": "liqueur"
  },
  {
    "id": "cranberry-juice",
    "name": "Cranberry juice",
    "category": "mixer"
  },
  {
    "id": "ginger-syrup",
    "name": "Ginger Syrup",
    "category": "sweetener"
  },
  {
    "id": "gold-rum",
    "name": "Gold rum",
    "category": "spirit"
  },
  {
    "id": "grand-marnier",
    "name": "Grand Marnier",
    "category": "other"
  },
  {
    "id": "grape-soda",
    "name": "Grape Soda",
    "category": "mixer"
  },
  {
    "id": "green-chartreuse",
    "name": "Green Chartreuse",
    "category": "liqueur"
  },
  {
    "id": "irish-whiskey",
    "name": "Irish whiskey",
    "category": "spirit"
  },
  {
    "id": "islay-single-malt-scotch",
    "name": "Islay single malt Scotch",
    "category": "spirit"
  },
  {
    "id": "lemon-peel",
    "name": "Lemon peel",
    "category": "other"
  },
  {
    "id": "light-cream",
    "name": "Light cream",
    "category": "mixer"
  },
  {
    "id": "lillet-blanc",
    "name": "Lillet Blanc",
    "category": "other"
  },
  {
    "id": "maraschino-cherry",
    "name": "Maraschino Cherry",
    "category": "liqueur"
  },
  {
    "id": "orange",
    "name": "Orange",
    "category": "citrus"
  },
  {
    "id": "orange-curacao",
    "name": "Orange Curacao",
    "category": "liqueur"
  },
  {
    "id": "orgeat-syrup",
    "name": "Orgeat syrup",
    "category": "sweetener"
  },
  {
    "id": "pernod",
    "name": "Pernod",
    "category": "other"
  },
  {
    "id": "peychaud-bitters",
    "name": "Peychaud bitters",
    "category": "liqueur"
  },
  {
    "id": "pineapple",
    "name": "Pineapple",
    "category": "other"
  },
  {
    "id": "powdered-sugar",
    "name": "Powdered sugar",
    "category": "sweetener"
  },
  {
    "id": "raspberry-liqueur",
    "name": "Raspberry Liqueur",
    "category": "liqueur"
  },
  {
    "id": "red-wine",
    "name": "Red wine",
    "category": "mixer"
  },
  {
    "id": "ricard",
    "name": "Ricard",
    "category": "other"
  },
  {
    "id": "salt",
    "name": "Salt",
    "category": "other"
  },
  {
    "id": "sweet-and-sour",
    "name": "Sweet and sour",
    "category": "other"
  },
  {
    "id": "vanilla-extract",
    "name": "Vanilla extract",
    "category": "other"
  },
  {
    "id": "water",
    "name": "Water",
    "category": "mixer"
  },
  {
    "id": "whipped-cream",
    "name": "Whipped cream",
    "category": "mixer"
  }
];
