// This file is generated by scripts/import-cocktails.mjs. Do not edit by hand.

export const starterIngredients = [
  "vodka",
  "gin",
  "white-rum",
  "tequila",
  "bourbon",
  "campari",
  "triple-sec",
  "sweet-vermouth",
  "tonic",
  "cola",
  "soda-water",
  "ginger-beer",
  "orange-juice",
  "cranberry-juice",
  "lime-juice",
  "lemon-juice",
  "angostura",
  "ice"
];
